export const SET_SPINNER = 'SET_SPINNER'
export const ADD_AUTH_ALERT = 'ADD_AUTH_ALERT'
export const SET_AUTHENTICATED ='SET_AUTHENTICATED'

export const SET_TOKEN ='SET_TOKEN'
export const REMOVE_TOKEN= 'REMOVE_TOKEN'

export const SET_SERVICES='SET_SERVICES'
export const SET_USER='SET_USER'